# Generated by Django 3.2.5 on 2022-07-16 06:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20220712_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephoneNumber',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('target_number', models.CharField(max_length=9)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
                ('telephone', models.ManyToManyField(blank=True, to='tel_attack.TelephoneNumber')),
            ],
        ),
    ]
