# Generated by Django 3.2.5 on 2022-07-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tel_attack', '0002_attack_text_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='text_message',
            field=models.TextField(default='hi', max_length=200),
        ),
    ]
